[pytest]
DJANGO_SETTINGS_MODULE = backend.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v -W ignore
filterwarnings =
    ignore::DeprecationWarning:coreapi.utils:
    ignore::DeprecationWarning:setuptools.*: