# Generated by Django 5.2 on 2026-04-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0002_provider_providermodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="latency_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencerequest",
            name="model_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="inferencerequest",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inference_requests",
                to="inference.provider",
            ),
        ),
    ]
