# Generated by Django 5.2 on 2026-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0003_inferencerequest_latency_ms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="callback_url",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="last_heartbeat_at",
        ),
        migrations.AddField(
            model_name="provider",
            name="agent_port",
            field=models.PositiveIntegerField(default=443),
        ),
        migrations.AddField(
            model_name="provider",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Bumped on every successful proxied request and every successful liveness probe.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="registered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="tailnet_hostname",
            field=models.CharField(
                blank=True,
                help_text="Tailscale MagicDNS hostname inside the inference.club tailnet (e.g. 'club-host-17'). Empty until the agent has registered.",
                max_length=255,
            ),
        ),
    ]
