# Generated by Django 5.2 on 2026-05-30 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0008_model_metadata_and_ttft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providermodel',
            name='hf_repo_id',
            field=models.CharField(blank=True, help_text="The HuggingFace repo id this deployment serves, when declared (e.g. 'Qwen/Qwen3-30B-A3B'). Drives the catalog slug / pooling. Blank for live-discovered or custom models.", max_length=255),
        ),
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('hf_repo_id', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_custom', models.BooleanField(default=False, help_text='True for models with no HuggingFace repo (custom fine-tunes / local-only weights).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Reserved for catalog enrichment (modalities, native context, recommended serving profile) in a later phase.')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='providermodel',
            name='catalog_model',
            field=models.ForeignKey(blank=True, help_text="The logical catalog model this deployment serves. Many providers' deployments share one CatalogModel — that pooling is what aggregates capacity for a model across the network.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='inference.catalogmodel'),
        ),
    ]
