# Generated by Django 5.2 on 2026-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0009_providermodel_hf_repo_id_catalogmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='architecture',
            field=models.CharField(blank=True, help_text="e.g. 'Qwen2_5_VLForConditionalGeneration'.", max_length=128),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='hf_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last successful HuggingFace enrichment.', null=True),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='input_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='native_context_length',
            field=models.PositiveIntegerField(blank=True, help_text='config.json max_position_embeddings (the ceiling).', null=True),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='output_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='supported_features',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['reasoning', 'tools']."),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Raw HF subset (pipeline_tag, library_name, gated, downloads, likes, model_type) + future fields (recommended serving profile).'),
        ),
    ]
