# Generated by Django 5.2 on 2026-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0010_catalogmodel_architecture_catalogmodel_hf_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermodel',
            name='served_context_len',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
