# Generated by Django 5.2 on 2026-05-31 19:53

import apps.inference.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0011_providermodel_served_context_len"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="audio_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("llm", "Language model"),
                    ("stt", "Speech to text"),
                    ("tts", "Text to speech"),
                ],
                default="llm",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="inferencerequest",
            name="inference_type",
            field=models.CharField(
                choices=[
                    ("LLM", "Language Model"),
                    ("STT", "Speech to Text"),
                    ("IMAGE", "Image Generation"),
                    ("VIDEO", "Video Generation"),
                    ("TTS", "Text to Speech"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("INPUT_AUDIO", "Input audio"),
                            ("OUTPUT_AUDIO", "Output audio"),
                            ("OUTPUT_IMAGE", "Output image"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        upload_to=apps.inference.models.media_asset_upload_to,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Audio/video duration, when known.",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inference_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="inference.inferencerequest",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "created_on"],
                        name="inference_m_user_id_707966_idx",
                    )
                ],
            },
        ),
    ]
