# Generated by Django 5.2 on 2026-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0012_inferencerequest_audio_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerservice",
            name="declared_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Operator-declared capabilities of THIS deployment, from the manifest's services[].features (e.g. ['timestamps'] when an STT service is served with a ForcedAligner so verbose_json returns word timings). Per-deployment because the same model may or may not expose a feature depending on how it was launched.",
            ),
        ),
    ]
