# Generated by Django 5.2 on 2026-05-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0013_providerservice_declared_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="image_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INPUT_AUDIO", "Input audio"),
                    ("OUTPUT_AUDIO", "Output audio"),
                    ("INPUT_IMAGE", "Input image"),
                    ("OUTPUT_IMAGE", "Output image"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="providerservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("llm", "Language model"),
                    ("stt", "Speech to text"),
                    ("tts", "Text to speech"),
                    ("image", "Image generation"),
                ],
                default="llm",
                max_length=16,
            ),
        ),
    ]
