# Generated by Django 5.2 on 2026-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0016_contentreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogmodel",
            name="architecture",
        ),
        migrations.RemoveField(
            model_name="catalogmodel",
            name="hf_synced_at",
        ),
        migrations.AlterField(
            model_name="catalogmodel",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Operator-declared extras (e.g. recommended serving profile).",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmodel",
            name="native_context_length",
            field=models.PositiveIntegerField(
                blank=True, help_text="Declared context-window ceiling.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="providermodel",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Operator-set overrides for the OpenRouter-style model catalog (e.g. name, quantization, context_length, max_output_length, input/output_modalities, supported_features, supported_sampling_parameters). The linked catalog model + defaults fill the rest.",
            ),
        ),
    ]
