# Generated by Django 5.2 on 2026-06-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0017_remove_catalogmodel_architecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencerequest',
            name='inference_type',
            field=models.CharField(choices=[('LLM', 'Language Model'), ('STT', 'Speech to Text'), ('IMAGE', 'Image Generation'), ('VIDEO', 'Video Generation'), ('TTS', 'Text to Speech'), ('MESH', 'Image to 3D')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('INPUT_AUDIO', 'Input audio'), ('OUTPUT_AUDIO', 'Output audio'), ('INPUT_IMAGE', 'Input image'), ('OUTPUT_IMAGE', 'Output image'), ('OUTPUT_MODEL', 'Output 3D model')], max_length=16),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='service_type',
            field=models.CharField(choices=[('llm', 'Language model'), ('stt', 'Speech to text'), ('tts', 'Text to speech'), ('image', 'Image generation'), ('mesh', 'Image to 3D')], default='llm', max_length=16),
        ),
    ]
