# Generated by Django 5.2 on 2026-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0018_alter_inferencerequest_inference_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inferencerequest",
            name="inference_type",
            field=models.CharField(
                choices=[
                    ("LLM", "Language Model"),
                    ("STT", "Speech to Text"),
                    ("IMAGE", "Image Generation"),
                    ("VIDEO", "Video Generation"),
                    ("TTS", "Text to Speech"),
                    ("MESH", "Image to 3D"),
                    ("MUSIC", "Music Generation"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providerservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("llm", "Language model"),
                    ("stt", "Speech to text"),
                    ("tts", "Text to speech"),
                    ("image", "Image generation"),
                    ("mesh", "Image to 3D"),
                    ("music", "Music generation"),
                ],
                default="llm",
                max_length=16,
            ),
        ),
    ]
