# Generated by Django 5.2 on 2026-06-11 17:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_item_positions(apps, schema_editor):
    """Give existing collection items real playlist positions (0..n-1 per
    collection, in order added). Until now every add wrote position=0, so the
    Meta ordering's -created_on tiebreak was the de-facto order."""
    CollectionItem = apps.get_model("inference", "CollectionItem")
    current_collection = None
    pos = 0
    batch = []
    for item in CollectionItem.objects.order_by(
        "collection_id", "created_on", "id"
    ).iterator():
        if item.collection_id != current_collection:
            current_collection = item.collection_id
            pos = 0
        if item.position != pos:
            item.position = pos
            batch.append(item)
        pos += 1
    if batch:
        CollectionItem.objects.bulk_update(batch, ["position"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0020_video_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="cover_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inference.inferencerequest",
            ),
        ),
        migrations.RunPython(
            backfill_item_positions, migrations.RunPython.noop
        ),
    ]
