# Generated by Django 5.2 on 2026-06-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0021_media_playback_cover_and_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="featured_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
