# Generated by Django 5.2 on 2026-06-13 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0024_backfill_manifest_revisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencerequest',
            name='inference_type',
            field=models.CharField(choices=[('LLM', 'Language Model'), ('STT', 'Speech to Text'), ('IMAGE', 'Image Generation'), ('VIDEO', 'Video Generation'), ('TTS', 'Text to Speech'), ('MESH', 'Image to 3D'), ('MUSIC', 'Music Generation'), ('VOICE', 'Voice Cloning')], max_length=32),
        ),
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('speaker_name', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True, default='')),
                ('transcript_source', models.CharField(choices=[('stt', 'Auto (speech-to-text)'), ('manual', 'Manual'), ('edited', 'Edited')], default='manual', max_length=8)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to='inference.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['speaker_name', '-is_default', '-created_on'],
                'indexes': [models.Index(fields=['user', 'speaker_name', 'created_on'], name='inference_v_user_id_b44a96_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'speaker_name'), name='one_default_voice_sample_per_speaker')],
            },
        ),
    ]
