# Generated by Django 5.2 on 2026-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0030_episode_segment_variant_segment_selected_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="grade",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="transcript",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="segment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("flagged", "Flagged"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
