# Generated by Django 5.2 on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0031_variant_grade_variant_transcript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="voice_model",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="episode",
            name="voice_sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="episodes",
                to="inference.voicesample",
            ),
        ),
    ]
