# Generated by Django 5.2 on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0032_episode_voice_model_episode_voice_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="enhanced_audio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inference.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="enhanced_words",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="variant",
            name="trim_intervals",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
