# Generated by Django 5.2 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0033_variant_enhanced_audio_trim_intervals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("flagged", "Flagged"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
