# Generated by Django 5.2 on 2026-06-23 00:59

import apps.inference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0037_chatthread_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerservice",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional custom logo; falls back to the engine glyph.",
                max_length=512,
                null=True,
                upload_to=apps.inference.models.service_logo_upload_to,
            ),
        ),
    ]
