# Generated by Django 5.2 on 2026-06-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _host_gpus(host: dict) -> list[dict]:
    """Inline copy of the GPU normalizer (migrations must not import view code)."""
    out: list[dict] = []
    raw_list = host.get("gpus")
    if isinstance(raw_list, list) and raw_list:
        for i, g in enumerate(raw_list):
            if isinstance(g, dict):
                idx = g.get("index")
                out.append({
                    "index": idx if isinstance(idx, int) else i,
                    "vendor": str(g.get("vendor") or ""),
                    "model": str(g.get("model") or ""),
                    "vram_gb": g.get("vram_gb") if isinstance(g.get("vram_gb"), (int, float)) else None,
                })
            elif g:
                out.append({"index": i, "vendor": "", "model": str(g), "vram_gb": None})
        return out
    gpu = host.get("gpu")
    if isinstance(gpu, dict):
        count = gpu.get("count", 1)
        count = count if isinstance(count, int) and count >= 1 else 1
        vram = gpu.get("vram_gb") if isinstance(gpu.get("vram_gb"), (int, float)) else None
        for i in range(count):
            out.append({"index": i, "vendor": str(gpu.get("vendor") or ""),
                        "model": str(gpu.get("model") or ""), "vram_gb": vram})
    elif isinstance(gpu, str) and gpu.strip():
        out.append({"index": 0, "vendor": "", "model": gpu.strip(), "vram_gb": None})
    return out


def backfill(apps, schema_editor):
    Provider = apps.get_model("inference", "Provider")
    Host = apps.get_model("inference", "Host")
    Gpu = apps.get_model("inference", "Gpu")
    ProviderService = apps.get_model("inference", "ProviderService")
    InferenceRequest = apps.get_model("inference", "InferenceRequest")

    for provider in Provider.objects.all():
        manifest = getattr(provider, "manifest", None)
        parsed = getattr(manifest, "parsed", None) if manifest else None
        hosts = parsed.get("hosts") if isinstance(parsed, dict) else None
        hosts_by_id = {}
        for h in hosts or []:
            if not isinstance(h, dict):
                continue
            hid = h.get("id")
            if not isinstance(hid, str) or not hid.strip():
                continue
            hid = hid.strip()
            host = Host.objects.create(
                provider=provider, host_id=hid,
                hostname=str(h.get("hostname") or ""),
                address=str(h.get("address") or ""),
                notes=str(h.get("notes") or ""), is_active=True,
            )
            hosts_by_id[hid] = host
            for gd in _host_gpus(h):
                Gpu.objects.create(host=host, is_active=True, **gd)
        # Link services to their host.
        for svc in provider.services.all():
            host = hosts_by_id.get(svc.manifest_host_id)
            if host is not None:
                svc.host = host
                svc.save(update_fields=["host"])

    # Backfill request → host/gpu from the dispatch_meta snapshot.
    qs = InferenceRequest.objects.exclude(dispatch_meta={}).filter(
        provider__isnull=False, host__isnull=True
    ).select_related("provider")
    for req in qs.iterator():
        meta = req.dispatch_meta or {}
        hid = meta.get("host_id")
        if not hid:
            continue
        host = Host.objects.filter(provider=req.provider, host_id=hid).first()
        if host is None:
            continue
        req.host = host
        gpus = list(host.gpus.all())
        if len(gpus) == 1:
            req.gpu = gpus[0]
        req.save(update_fields=["host", "gpu"])


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0038_providerservice_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename (not drop+add) so existing services keep their manifest host id,
        # which the backfill below uses to link them to the new Host rows.
        migrations.RenameField(
            model_name='providerservice',
            old_name='host_id',
            new_name='manifest_host_id',
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='manifest_host_id',
            field=models.CharField(blank=True, help_text='Manifest host id (the join key).', max_length=255),
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='0-based device index on the host.')),
                ('vendor', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', help_text="GPU model name, e.g. 'NVIDIA GeForce RTX 4090'.", max_length=255)),
                ('vram_gb', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='inferencerequest',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_requests', to='inference.gpu'),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('host_id', models.CharField(help_text="The manifest host id (e.g. 'a1', 'spark'); the join key that services and requests reference.", max_length=255)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='False once the host disappears from the latest manifest (kept for history rather than deleted).')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='inference.provider')),
            ],
            options={
                'ordering': ['host_id'],
            },
        ),
        migrations.AddField(
            model_name='gpu',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='inference.host'),
        ),
        migrations.AddField(
            model_name='inferencerequest',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_requests', to='inference.host'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='inference.host'),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('provider', 'host_id'), name='unique_host_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='gpu',
            constraint=models.UniqueConstraint(fields=('host', 'index'), name='unique_gpu_index_per_host'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
