# Generated by Django 5.2 on 2026-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0039_remove_providerservice_host_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="tailnet_addr",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "The agent's actual tailnet IP, reported on its heartbeat "
                    "once it has joined (e.g. '100.68.155.114'). Preferred dial "
                    "target: it routes straight over WireGuard via the SOCKS "
                    "proxy, so it's immune to MagicDNS hostname drift when a node "
                    "rejoins and Tailscale uniquifies its name (club-host-1 → "
                    "club-host-1-1). Falls back to tailnet_hostname when empty."
                ),
                max_length=64,
            ),
        ),
    ]
