# Generated by Django 5.2 on 2026-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0040_provider_tailnet_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='tailnet_hostname',
            field=models.CharField(blank=True, help_text="Tailscale MagicDNS hostname inside the inference.club tailnet (e.g. 'club-host-17'). Empty until the agent has registered. Kept as a human-readable label; the dial target is tailnet_addr when set.", max_length=255),
        ),
    ]
