# Generated by Django 5.2 on 2026-06-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0042_mediaasset_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('INPUT_AUDIO', 'Input audio'), ('OUTPUT_AUDIO', 'Output audio'), ('INPUT_IMAGE', 'Input image'), ('OUTPUT_IMAGE', 'Output image'), ('INPUT_VIDEO', 'Input video'), ('OUTPUT_MODEL', 'Output 3D model'), ('OUTPUT_VIDEO', 'Output video'), ('INPUT_DOC', 'Input document'), ('OUTPUT_DOC', 'Output document'), ('OUTPUT_SUBTITLE', 'Output subtitle')], max_length=16),
        ),
    ]
