# Generated by Django 5.2 on 2026-06-26 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0043_alter_mediaasset_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('model_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('context_length', models.IntegerField(blank=True, null=True)),
                ('input_modalities', models.JSONField(blank=True, default=list)),
                ('supported_features', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'model_id'],
                'indexes': [models.Index(fields=['user', 'provider'], name='inference_p_user_id_cb3788_idx')],
                'unique_together': {('user', 'provider', 'model_id')},
            },
        ),
    ]
