# Generated by Django 5.2 on 2026-07-09 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0047_cluster_control_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='agent_control_token',
            field=models.CharField(blank=True, default='', help_text="Bearer secret for the agent's scale endpoint; must match the agent's AGENT_CONTROL_TOKEN. Empty = read-only, no actuation (PRD 21).", max_length=128),
        ),
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deployment', models.CharField(max_length=255)),
                ('service', models.CharField(blank=True, default='', max_length=255)),
                ('box', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(choices=[('park', 'Park'), ('unpark', 'Unpark')], max_length=16)),
                ('replicas', models.PositiveSmallIntegerField()),
                ('result', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_actions', to='inference.provider')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
