import * as pulumi from "@pulumi/pulumi";

// All Pulumi config the program needs. Keeping reads in one place so the rest
// of the code is typed and so the required vs. auto-generated split is obvious.
//
// User-supplied:
//   - HCLOUD_TOKEN env var   : Hetzner Cloud API token; consumed directly by
//                              the hcloud provider, not via Pulumi config
//   - ghcrToken (Pulumi cfg) : GitHub PAT (classic, scope: read:packages) so
//                              the VPS can pull private images from GHCR
//   - sshPublicKey           : OpenSSH public key (stable across deploys; we
//                              used to auto-generate via @pulumi/tls but it
//                              regenerated unpredictably and replaced the
//                              server, losing data each time)
//   - sshPrivateKey          : matching private key for SSH-based deployment
//
// Optional — if unset, the deployed site renders but GitHub OAuth login is broken:
//   - githubOauthClientId    : production GitHub OAuth App client id
//   - githubOauthClientSecret: production GitHub OAuth App client secret
//
// Auto-generated by Pulumi resources (no user input needed):
//   - SSH keypair            : @pulumi/tls produces it; private half drives
//                              the SSH connection in deployment.ts, public
//                              half is registered with Hetzner
//   - djangoSecretKey        : @pulumi/random
//   - postgresPassword       : @pulumi/random
const cfg = new pulumi.Config();

export const stackConfig = {
    domain: cfg.get("domain") ?? "inference.club",
    hcloudLocation: cfg.get("hcloudLocation") ?? "nbg1",
    serverType: cfg.get("serverType") ?? "cx23",

    // GCS media buckets live next to the Hetzner box (nbg1 = Nuremberg, so
    // europe-west3 = Frankfurt) to keep backend<->bucket latency low. The GCP
    // project itself comes from the `gcp:project` provider config.
    gcsLocation: cfg.get("gcsLocation") ?? "EUROPE-WEST3",

    backendImage:
        cfg.get("backendImage") ??
        "ghcr.io/inference-club/inference-club-backend:latest",
    frontendImage:
        cfg.get("frontendImage") ??
        "ghcr.io/inference-club/inference-club-frontend:latest",

    // Used as the docker login username on the VPS. The org name works with a
    // PAT created by any user who can read its packages.
    ghcrUsername: cfg.get("ghcrUsername") ?? "inference-club",

    ghcrToken: cfg.requireSecret("ghcrToken"),

    // Tailscale: optional during initial bootstrap. Empty values let the
    // stack come up without Tailscale wired (the server just won't be able
    // to reach any agents). Set the secrets to enable inference end-to-end.
    tailscaleTailnet: cfg.get("tailscaleTailnet") ?? "",
    tailscaleStaticAuthkey: pulumi
        .output(cfg.getSecret("tailscaleStaticAuthkey"))
        .apply((v) => v ?? ""),
    tailscaleWebAuthkey: pulumi
        .output(cfg.getSecret("tailscaleWebAuthkey"))
        .apply((v) => v ?? ""),

    sshPublicKey: cfg.requireSecret("sshPublicKey"),

    // The SSH private key comes in via env (DEPLOY_SSH_PRIVATE_KEY) rather
    // than Pulumi config, because pulumi/actions's config-map is YAML and
    // can't carry multi-line values cleanly. The repo secret holds the key
    // base64-encoded so it travels as a single line through workflow env;
    // we decode here.
    sshPrivateKey: pulumi.secret(
        (() => {
            const b64 = process.env.DEPLOY_SSH_PRIVATE_KEY;
            if (!b64) {
                throw new Error(
                    "DEPLOY_SSH_PRIVATE_KEY env var is missing. Set the " +
                        "repo secret of the same name (base64-encoded PEM).",
                );
            }
            return Buffer.from(b64, "base64").toString("utf8");
        })(),
    ),

    // Optional — default to empty string so the backend container starts; the
    // OAuth login button just won't do anything until you set them.
    // getSecret returns Output<string> | undefined when the key is unset, so
    // we wrap with pulumi.output() to flatten that into a single Output<string>.
    githubOauthClientId: pulumi
        .output(cfg.getSecret("githubOauthClientId"))
        .apply((v) => v ?? ""),
    githubOauthClientSecret: pulumi
        .output(cfg.getSecret("githubOauthClientSecret"))
        .apply((v) => v ?? ""),
};

export type StackConfig = typeof stackConfig;
