import * as pulumi from "@pulumi/pulumi";

// All Pulumi config the program needs. Keeping reads in one place so the rest
// of the code is typed and so the required vs. auto-generated split is obvious.
//
// User-supplied:
//   - HCLOUD_TOKEN env var   : Hetzner Cloud API token; consumed directly by
//                              the hcloud provider, not via Pulumi config
//   - ghcrToken (Pulumi cfg) : GitHub PAT (classic, scope: read:packages) so
//                              the VPS can pull private images from GHCR
//
// Optional — if unset, the deployed site renders but GitHub OAuth login is broken:
//   - githubOauthClientId    : production GitHub OAuth App client id
//   - githubOauthClientSecret: production GitHub OAuth App client secret
//
// Auto-generated by Pulumi resources (no user input needed):
//   - SSH keypair            : @pulumi/tls produces it; private half drives
//                              the SSH connection in deployment.ts, public
//                              half is registered with Hetzner
//   - djangoSecretKey        : @pulumi/random
//   - postgresPassword       : @pulumi/random
const cfg = new pulumi.Config();

export const stackConfig = {
    domain: cfg.get("domain") ?? "inference.club",
    hcloudLocation: cfg.get("hcloudLocation") ?? "nbg1",
    serverType: cfg.get("serverType") ?? "cx22",

    backendImage:
        cfg.get("backendImage") ??
        "ghcr.io/inference-club/inference-club-backend:latest",
    frontendImage:
        cfg.get("frontendImage") ??
        "ghcr.io/inference-club/inference-club-frontend:latest",

    // Used as the docker login username on the VPS. The org name works with a
    // PAT created by any user who can read its packages.
    ghcrUsername: cfg.get("ghcrUsername") ?? "inference-club",

    ghcrToken: cfg.requireSecret("ghcrToken"),

    // Optional — default to empty string so the backend container starts; the
    // OAuth login button just won't do anything until you set them.
    // getSecret returns Output<string> | undefined when the key is unset, so
    // we wrap with pulumi.output() to flatten that into a single Output<string>.
    githubOauthClientId: pulumi
        .output(cfg.getSecret("githubOauthClientId"))
        .apply((v) => v ?? ""),
    githubOauthClientSecret: pulumi
        .output(cfg.getSecret("githubOauthClientSecret"))
        .apply((v) => v ?? ""),
};

export type StackConfig = typeof stackConfig;
