# Generated by Django 5.2 on 2026-05-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="routing_preference",
            field=models.CharField(
                choices=[
                    ("ANY", "Use any provider"),
                    ("PREFER_OWN", "Prefer my own nodes"),
                    ("ONLY_OWN", "Only my own nodes"),
                ],
                default="ANY",
                help_text="Which providers to route this user's requests to when multiple serve the same model.",
                max_length=16,
                verbose_name="routing preference",
            ),
        ),
    ]
