# Generated by Django 5.2 on 2026-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_routing_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_request_visibility",
            field=models.CharField(
                default="UNLISTED",
                help_text="Visibility applied to new inference requests unless overridden.",
                max_length=12,
                verbose_name="default request visibility",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="public_profile_enabled",
            field=models.BooleanField(
                default=True, verbose_name="public profile enabled"
            ),
        ),
    ]
