# Generated by Django 5.2 on 2026-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_default_request_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_collection_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="New inference requests are added to this collection (created on first use) unless the request specifies another.",
                max_length=120,
                verbose_name="default collection name",
            ),
        ),
    ]
