# Generated by Django 5.2 on 2026-06-12 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_default_collection_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_signin_enabled", models.BooleanField(default=False)),
                ("passcode_signin_enabled", models.BooleanField(default=True)),
                ("max_active_guests", models.PositiveIntegerField(default=100)),
                (
                    "guest_creation_rate",
                    models.CharField(default="5/hour", max_length=20),
                ),
                (
                    "passcode_attempt_rate",
                    models.CharField(default="10/hour", max_length=20),
                ),
                (
                    "anon_inference_rate",
                    models.CharField(default="15/min", max_length=20),
                ),
                ("anon_models_rate", models.CharField(default="60/min", max_length=20)),
                ("guest_message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "access policy",
                "verbose_name_plural": "access policy",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("GITHUB", "GitHub"),
                    ("GUEST", "Guest"),
                    ("PASSCODE", "Passcode"),
                ],
                db_index=True,
                default="GITHUB",
                max_length=12,
                verbose_name="account type",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="alias_regenerated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="anon_alias",
            field=models.SlugField(
                blank=True,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="anonymous alias",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="handle",
            field=models.SlugField(
                blank=True, max_length=80, null=True, unique=True, verbose_name="handle"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="session_epoch",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="use_anon_alias",
            field=models.BooleanField(
                default=False, verbose_name="use anonymous alias"
            ),
        ),
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Admin note, e.g. "for Max".',
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
