# Generated by Django 5.2 on 2026-06-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_backfill_handles"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="brave_api_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
