# Generated by Django 5.2 on 2026-06-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fallback_model',
            field=models.CharField(blank=True, default='', help_text='LLM model to fall back to when the chosen one is unavailable.', max_length=255, verbose_name='fallback model'),
        ),
    ]
