from django.urls import path

from .job_views import (
    BatchDetailView,
    BatchListCreateView,
    JobCancelView,
    JobDetailView,
    JobListView,
    JobRetryView,
    MediaAssetDetailView,
    WorkflowDetailView,
    WorkflowForkRunView,
    WorkflowForkTemplateView,
    WorkflowGateView,
    WorkflowListCreateView,
    WorkflowRunDetailView,
    WorkflowRunFromSavedView,
    WorkflowRunListCreateView,
    WorkflowStepRerunView,
    WorkflowSuggestionListView,
    WorkflowTemplateListView,
)
from .studio_views import (
    EpisodeDetailView,
    EpisodeListCreateView,
    SegmentDetailView,
    SegmentListCreateView,
    SegmentProcessView,
    SegmentRegenerateView,
    SegmentReorderView,
    VariantSelectView,
)
from .openai_views import (
    AudioEnhanceView,
    AudioSpeechView,
    AudioTranscriptionsView,
    AudioVoicesView,
    ChatCompletionsView,
    CompletionsView,
    ComposeView,
    ImageEditsView,
    ImageGenerationsView,
    Mesh3DGenerationsView,
    ModelsView,
    MusicGenerationsView,
    ScrapeView,
    VideoGenerationsView,
    VoiceGenerationsView,
)

app_name = "openai"

urlpatterns = [
    path("models", ModelsView.as_view(), name="models"),
    path("models/", ModelsView.as_view()),
    path("chat/completions", ChatCompletionsView.as_view(), name="chat-completions"),
    path("chat/completions/", ChatCompletionsView.as_view()),
    path("completions", CompletionsView.as_view(), name="completions"),
    path("completions/", CompletionsView.as_view()),
    path("audio/transcriptions", AudioTranscriptionsView.as_view(), name="audio-transcriptions"),
    path("audio/transcriptions/", AudioTranscriptionsView.as_view()),
    path("audio/speech", AudioSpeechView.as_view(), name="audio-speech"),
    path("audio/speech/", AudioSpeechView.as_view()),
    path("audio/voices", AudioVoicesView.as_view(), name="audio-voices"),
    path("audio/voices/", AudioVoicesView.as_view()),
    path("audio/enhance", AudioEnhanceView.as_view(), name="audio-enhance"),
    path("audio/enhance/", AudioEnhanceView.as_view()),
    path("images/generations", ImageGenerationsView.as_view(), name="images-generations"),
    path("images/generations/", ImageGenerationsView.as_view()),
    path("images/edits", ImageEditsView.as_view(), name="images-edits"),
    path("images/edits/", ImageEditsView.as_view()),
    path("3d/generations", Mesh3DGenerationsView.as_view(), name="mesh-generations"),
    path("3d/generations/", Mesh3DGenerationsView.as_view()),
    path("music/generations", MusicGenerationsView.as_view(), name="music-generations"),
    path("music/generations/", MusicGenerationsView.as_view()),
    path("videos/generations", VideoGenerationsView.as_view(), name="videos-generations"),
    path("videos/generations/", VideoGenerationsView.as_view()),
    path("videos/compose", ComposeView.as_view(), name="videos-compose"),
    path("videos/compose/", ComposeView.as_view()),
    path("voice/generations", VoiceGenerationsView.as_view(), name="voice-generations"),
    path("voice/generations/", VoiceGenerationsView.as_view()),
    path("scrape", ScrapeView.as_view(), name="scrape"),
    path("scrape/", ScrapeView.as_view()),
    # --- media assets + provenance (PRD 12) ---
    path("assets/<int:id>", MediaAssetDetailView.as_view(), name="asset-detail"),
    path("assets/<int:id>/", MediaAssetDetailView.as_view()),
    # --- narration studio (PRD 12 §5.4) ---
    path("episodes", EpisodeListCreateView.as_view(), name="episodes"),
    path("episodes/", EpisodeListCreateView.as_view()),
    path("episodes/<int:id>", EpisodeDetailView.as_view(), name="episode-detail"),
    path("episodes/<int:id>/", EpisodeDetailView.as_view()),
    # Reorder must precede the generic segments collection route.
    path("episodes/<int:id>/segments/reorder", SegmentReorderView.as_view(), name="segment-reorder"),
    path("episodes/<int:id>/segments/reorder/", SegmentReorderView.as_view()),
    path("episodes/<int:id>/segments", SegmentListCreateView.as_view(), name="segments"),
    path("episodes/<int:id>/segments/", SegmentListCreateView.as_view()),
    path("segments/<int:id>", SegmentDetailView.as_view(), name="segment-detail"),
    path("segments/<int:id>/", SegmentDetailView.as_view()),
    path("segments/<int:id>/variants/<int:vid>/select", VariantSelectView.as_view(), name="variant-select"),
    path("segments/<int:id>/variants/<int:vid>/select/", VariantSelectView.as_view()),
    path("segments/<int:id>/process", SegmentProcessView.as_view(), name="segment-process"),
    path("segments/<int:id>/process/", SegmentProcessView.as_view()),
    path("segments/<int:id>/regenerate", SegmentRegenerateView.as_view(), name="segment-regenerate"),
    path("segments/<int:id>/regenerate/", SegmentRegenerateView.as_view()),
    # --- async jobs / batches / workflows (PRD 10) ---
    path("jobs", JobListView.as_view(), name="jobs"),
    path("jobs/", JobListView.as_view()),
    path("jobs/<int:id>", JobDetailView.as_view(), name="job-detail"),
    path("jobs/<int:id>/", JobDetailView.as_view()),
    path("jobs/<int:id>/cancel", JobCancelView.as_view(), name="job-cancel"),
    path("jobs/<int:id>/cancel/", JobCancelView.as_view()),
    path("jobs/<int:id>/retry", JobRetryView.as_view(), name="job-retry"),
    path("jobs/<int:id>/retry/", JobRetryView.as_view()),
    path("batches", BatchListCreateView.as_view(), name="batches"),
    path("batches/", BatchListCreateView.as_view()),
    path("batches/<int:id>", BatchDetailView.as_view(), name="batch-detail"),
    path("batches/<int:id>/", BatchDetailView.as_view()),
    path("workflows/templates", WorkflowTemplateListView.as_view(), name="workflow-templates"),
    path("workflows/templates/", WorkflowTemplateListView.as_view()),
    path("workflows/suggestions", WorkflowSuggestionListView.as_view(), name="workflow-suggestions"),
    path("workflows/suggestions/", WorkflowSuggestionListView.as_view()),
    path("workflows/runs", WorkflowRunListCreateView.as_view(), name="workflow-runs"),
    path("workflows/runs/", WorkflowRunListCreateView.as_view()),
    path("workflows/runs/<int:id>", WorkflowRunDetailView.as_view(), name="workflow-run-detail"),
    path("workflows/runs/<int:id>/", WorkflowRunDetailView.as_view()),
    # Single-step re-run must precede the generic gate <action> path below.
    path(
        "workflows/runs/<int:id>/steps/<str:step_id>/rerun",
        WorkflowStepRerunView.as_view(), name="workflow-step-rerun",
    ),
    path(
        "workflows/runs/<int:id>/steps/<str:step_id>/rerun/",
        WorkflowStepRerunView.as_view(),
    ),
    path(
        "workflows/runs/<int:id>/steps/<str:step_id>/<str:action>",
        WorkflowGateView.as_view(), name="workflow-gate",
    ),
    path(
        "workflows/runs/<int:id>/steps/<str:step_id>/<str:action>/",
        WorkflowGateView.as_view(),
    ),
    # --- saved workflows / authoring (PRD 11) ---
    path("workflows", WorkflowListCreateView.as_view(), name="workflows"),
    path("workflows/", WorkflowListCreateView.as_view()),
    path("workflows/from-template/<str:key>", WorkflowForkTemplateView.as_view(), name="workflow-fork-template"),
    path("workflows/from-template/<str:key>/", WorkflowForkTemplateView.as_view()),
    path("workflows/from-run/<int:run_id>", WorkflowForkRunView.as_view(), name="workflow-fork-run"),
    path("workflows/from-run/<int:run_id>/", WorkflowForkRunView.as_view()),
    path("workflows/<int:id>", WorkflowDetailView.as_view(), name="workflow-detail"),
    path("workflows/<int:id>/", WorkflowDetailView.as_view()),
    path("workflows/<int:id>/runs", WorkflowRunFromSavedView.as_view(), name="workflow-run-saved"),
    path("workflows/<int:id>/runs/", WorkflowRunFromSavedView.as_view()),
]
