from django.urls import path

from .job_views import (
    BatchDetailView,
    BatchListCreateView,
    JobCancelView,
    JobDetailView,
    JobListView,
    JobRetryView,
    WorkflowGateView,
    WorkflowRunDetailView,
    WorkflowRunListCreateView,
)
from .openai_views import (
    AudioSpeechView,
    AudioTranscriptionsView,
    AudioVoicesView,
    ChatCompletionsView,
    CompletionsView,
    ImageEditsView,
    ImageGenerationsView,
    Mesh3DGenerationsView,
    ModelsView,
    MusicGenerationsView,
    VideoGenerationsView,
    VoiceGenerationsView,
)

app_name = "openai"

urlpatterns = [
    path("models", ModelsView.as_view(), name="models"),
    path("models/", ModelsView.as_view()),
    path("chat/completions", ChatCompletionsView.as_view(), name="chat-completions"),
    path("chat/completions/", ChatCompletionsView.as_view()),
    path("completions", CompletionsView.as_view(), name="completions"),
    path("completions/", CompletionsView.as_view()),
    path("audio/transcriptions", AudioTranscriptionsView.as_view(), name="audio-transcriptions"),
    path("audio/transcriptions/", AudioTranscriptionsView.as_view()),
    path("audio/speech", AudioSpeechView.as_view(), name="audio-speech"),
    path("audio/speech/", AudioSpeechView.as_view()),
    path("audio/voices", AudioVoicesView.as_view(), name="audio-voices"),
    path("audio/voices/", AudioVoicesView.as_view()),
    path("images/generations", ImageGenerationsView.as_view(), name="images-generations"),
    path("images/generations/", ImageGenerationsView.as_view()),
    path("images/edits", ImageEditsView.as_view(), name="images-edits"),
    path("images/edits/", ImageEditsView.as_view()),
    path("3d/generations", Mesh3DGenerationsView.as_view(), name="mesh-generations"),
    path("3d/generations/", Mesh3DGenerationsView.as_view()),
    path("music/generations", MusicGenerationsView.as_view(), name="music-generations"),
    path("music/generations/", MusicGenerationsView.as_view()),
    path("videos/generations", VideoGenerationsView.as_view(), name="videos-generations"),
    path("videos/generations/", VideoGenerationsView.as_view()),
    path("voice/generations", VoiceGenerationsView.as_view(), name="voice-generations"),
    path("voice/generations/", VoiceGenerationsView.as_view()),
    # --- async jobs / batches / workflows (PRD 10) ---
    path("jobs", JobListView.as_view(), name="jobs"),
    path("jobs/", JobListView.as_view()),
    path("jobs/<int:id>", JobDetailView.as_view(), name="job-detail"),
    path("jobs/<int:id>/", JobDetailView.as_view()),
    path("jobs/<int:id>/cancel", JobCancelView.as_view(), name="job-cancel"),
    path("jobs/<int:id>/cancel/", JobCancelView.as_view()),
    path("jobs/<int:id>/retry", JobRetryView.as_view(), name="job-retry"),
    path("jobs/<int:id>/retry/", JobRetryView.as_view()),
    path("batches", BatchListCreateView.as_view(), name="batches"),
    path("batches/", BatchListCreateView.as_view()),
    path("batches/<int:id>", BatchDetailView.as_view(), name="batch-detail"),
    path("batches/<int:id>/", BatchDetailView.as_view()),
    path("workflows/runs", WorkflowRunListCreateView.as_view(), name="workflow-runs"),
    path("workflows/runs/", WorkflowRunListCreateView.as_view()),
    path("workflows/runs/<int:id>", WorkflowRunDetailView.as_view(), name="workflow-run-detail"),
    path("workflows/runs/<int:id>/", WorkflowRunDetailView.as_view()),
    path(
        "workflows/runs/<int:id>/steps/<str:step_id>/<str:action>",
        WorkflowGateView.as_view(), name="workflow-gate",
    ),
    path(
        "workflows/runs/<int:id>/steps/<str:step_id>/<str:action>/",
        WorkflowGateView.as_view(),
    ),
]
