from django.urls import path
from .openai_views import RetryInferenceRequestView
from .job_views import QueueSummaryView
from .views import (
    AgentHeartbeatView,
    AgentManifestView,
    AgentRegisterView,
    AllInferenceRequestView,
    AllProvidersListView,
    ApiKeyDetailView,
    ApiKeyListView,
    ChatThreadDetailView,
    ChatThreadView,
    ProviderClusterActivityView,
    ProviderClusterHistoryView,
    ProviderClusterRevisionView,
    ProviderClusterStateView,
    ProviderHostDetailView,
    BookmarkedRequestsView,
    CollectionDetailView,
    CollectionItemView,
    CollectionListCreateView,
    CollectionOrderView,
    FeaturedContentView,
    RequestCoverView,
    RequestFeatureView,
    InferenceRequestView,
    LeaderboardView,
    MediaAssetView,
    ModelCatalogView,
    NetworkStatusView,
    ProviderListView,
    RateLimitUsageView,
    ProviderManifestView,
    ProviderModelsCatalogView,
    ProviderServiceListView,
    ProviderServiceUpdateView,
    ServiceLogoView,
    ProviderUpdateView,
    RefreshProviderModelsView,
    RequestBookmarkView,
    RequestReportView,
    RequestStarView,
    RetrieveInferenceRequestView,
    SharedRequestView,
    StarredRequestsView,
    VoiceSampleDetailView,
    VoiceSampleListCreateView,
    VoiceSampleTranscribeView,
)

app_name = "inference"

urlpatterns = [
    path("requests/", InferenceRequestView.as_view(), name="inference-requests"),
    path(
        "requests/all/",
        AllInferenceRequestView.as_view(),
        name="inference-requests-all",
    ),
    path(
        "requests/starred/",
        StarredRequestsView.as_view(),
        name="inference-requests-starred",
    ),
    path(
        "requests/bookmarked/",
        BookmarkedRequestsView.as_view(),
        name="inference-requests-bookmarked",
    ),
    path(
        # <str:> so the opaque public_id resolves here; numeric PKs still match
        # (the view falls back to pk). Static routes above take precedence.
        "requests/<str:id>/",
        RetrieveInferenceRequestView.as_view(),
        name="inference-detail",
    ),
    path(
        "requests/<int:id>/star/",
        RequestStarView.as_view(),
        name="inference-request-star",
    ),
    path(
        "requests/<int:id>/bookmark/",
        RequestBookmarkView.as_view(),
        name="inference-request-bookmark",
    ),
    path(
        "requests/<int:id>/cover/",
        RequestCoverView.as_view(),
        name="inference-request-cover",
    ),
    path(
        "requests/<int:id>/feature/",
        RequestFeatureView.as_view(),
        name="inference-request-feature",
    ),
    path(
        "featured/",
        FeaturedContentView.as_view(),
        name="featured-content",
    ),
    path(
        "requests/<int:id>/report/",
        RequestReportView.as_view(),
        name="inference-request-report",
    ),
    path(
        "requests/<int:id>/retry/",
        RetryInferenceRequestView.as_view(),
        name="inference-request-retry",
    ),
    path(
        "shared/<str:share_token>/",
        SharedRequestView.as_view(),
        name="inference-shared",
    ),
    path(
        "collections/",
        CollectionListCreateView.as_view(),
        name="collection-list",
    ),
    path(
        "collections/<slug:slug>/",
        CollectionDetailView.as_view(),
        name="collection-detail",
    ),
    path(
        "collections/<slug:slug>/items/order/",
        CollectionOrderView.as_view(),
        name="collection-order",
    ),
    path(
        "collections/<slug:slug>/items/<int:request_id>/",
        CollectionItemView.as_view(),
        name="collection-item",
    ),
    path("threads/", ChatThreadView.as_view(), name="chat-thread-list"),
    path(
        "threads/<str:id>/",
        ChatThreadDetailView.as_view(),
        name="chat-thread-detail",
    ),
    path("api-keys/", ApiKeyListView.as_view(), name="api-key-list"),
    path("api-keys/<str:service>/", ApiKeyDetailView.as_view(), name="api-key-detail"),
    path("agent/register/", AgentRegisterView.as_view(), name="agent-register"),
    path("agent/heartbeat/", AgentHeartbeatView.as_view(), name="agent-heartbeat"),
    path("agent/manifest/", AgentManifestView.as_view(), name="agent-manifest"),
    path("providers/", ProviderListView.as_view(), name="provider-list"),
    path("providers/all/", AllProvidersListView.as_view(), name="provider-list-all"),
    path("providers/<int:id>/", ProviderUpdateView.as_view(), name="provider-detail"),
    path("network/", NetworkStatusView.as_view(), name="network-status"),
    path("queue/summary/", QueueSummaryView.as_view(), name="queue-summary"),
    path("models/", ModelCatalogView.as_view(), name="model-catalog"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("usage/", RateLimitUsageView.as_view(), name="rate-limit-usage"),
    path("assets/<str:ref>/", MediaAssetView.as_view(), name="media-asset"),
    path(
        "voice-samples/",
        VoiceSampleListCreateView.as_view(),
        name="voice-sample-list",
    ),
    path(
        "voice-samples/<int:id>/",
        VoiceSampleDetailView.as_view(),
        name="voice-sample-detail",
    ),
    path(
        "voice-samples/<int:id>/transcribe/",
        VoiceSampleTranscribeView.as_view(),
        name="voice-sample-transcribe",
    ),
    path(
        "provider/models/",
        ProviderModelsCatalogView.as_view(),
        name="provider-models-catalog",
    ),
    path("services/", ProviderServiceListView.as_view(), name="service-list"),
    path(
        "services/<int:id>/",
        ProviderServiceUpdateView.as_view(),
        name="service-detail",
    ),
    path(
        "services/<int:pk>/logo/",
        ServiceLogoView.as_view(),
        name="service-logo",
    ),
    path(
        "providers/<int:id>/refresh-models/",
        RefreshProviderModelsView.as_view(),
        name="provider-refresh-models",
    ),
    path(
        "providers/<int:id>/manifest/",
        ProviderManifestView.as_view(),
        name="provider-manifest",
    ),
    path(
        "providers/<int:id>/hosts/<str:host_id>/",
        ProviderHostDetailView.as_view(),
        name="provider-host-detail",
    ),
    path(
        "providers/<int:id>/cluster/",
        ProviderClusterStateView.as_view(),
        name="provider-cluster-state",
    ),
    path(
        "providers/<int:id>/cluster/activity/",
        ProviderClusterActivityView.as_view(),
        name="provider-cluster-activity",
    ),
    path(
        "providers/<int:id>/cluster/history/",
        ProviderClusterHistoryView.as_view(),
        name="provider-cluster-history",
    ),
    path(
        "providers/<int:id>/cluster/history/<int:rev_id>/",
        ProviderClusterRevisionView.as_view(),
        name="provider-cluster-revision",
    ),
]
